[package]
name = "HistDiff_standalone"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10.0"
ndarray = "0.16.1"
csv = "1.3.1"
dashmap = "6.1"
clap = "4.5"

[profile.test]
inherits = "release"
