[package]
name = "HistDiff_standalone"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10.0"
polars = "0.44.2"
ndarray = "0.16.1"
csv = "1.3.1"
dashmap = "6.1"

[profile.test]
inherits = "release"
